name: Deploy JS App to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read  # Required to fetch the repository content
  pages: write    # Allow deployment to GitHub Pages
  id-token: write # Required by actions/configure-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: "✅ Checkout code"
        uses: actions/checkout@v5

      # 2. Set up JDK 21
      - name: "⚙️ Set up JDK 21"
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Set up Gradle
      - name: "⚙️ Setup Gradle"
        uses: gradle/actions/setup-gradle@v4

      - name: Create Sekrets
        env:
          YAML: ${{ secrets.SEKRET_YAML_BASE64 }}
        run: echo "${YAML// /}" | base64 -d > composeApp/sekret.yaml

      - name: Create Google-Services
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
        run: echo "${GOOGLE_SERVICES// /}" | base64 -d > composeApp/google-services.json

      - name: Generate Sekrets
        run: ./gradlew composeApp:generateSekret

      - name: Build
        continue-on-error: true
        run: ./gradlew build

      # 4. Build the WasmJS App
      - name: "🛠️ Build WasmJS App"
        run: gradle :composeApp:jsBrowserDistribution

      # 5. Set up GitHub Pages
      - name: "📄 Configure GitHub Pages"
        uses: actions/configure-pages@v5

      # 6. Upload the built artifact to Pages
      - name: "📤 Upload GitHub Pages artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./composeApp/build/dist/js/productionExecutable

      # 7. Deploy to GitHub Pages
      - name: "🚀 Deploy to GitHub Pages"
        id: deployment
        uses: actions/deploy-pages@v4